In [1]:
import os
import pandas as pd

In [5]:
indir = '../../data/ADHD200/RawData'

In [7]:
csvs = [i for i in os.listdir(indir) if i.endswith('.csv')]
csvs.sort()

In [12]:
df1 = pd.read_csv(os.path.join(indir,csvs[0]))
df2 = pd.read_csv(os.path.join(indir,csvs[1]))

In [22]:
dfs = [pd.read_csv(os.path.join(indir,csv)) for csv in csvs]

In [20]:
df2.head()

,ScanDir ID,Site,Gender,Age,Handedness,DX,Secondary Dx,ADHD Measure,ADHD Index,Inattentive,...,Performance IQ,Full2 IQ,Full4 IQ,Med Status,QC_Rest_1,QC_Rest_2,QC_Rest_3,QC_Rest_4,QC_Anatomical_1,QC_Anatomical_2
0,2371032,3,0,10.73,1,0,NaN,2,47,55,...,119,NaN,122,1,1,NaN,NaN,NaN,1,NaN
1,2026113,3,0,12.99,1,1,NaN,2,90,89,...,108,NaN,106,1,1,NaN,NaN,NaN,1,NaN
2,3434578,3,0,8.12,1,0,NaN,2,42,42,...,98,NaN,89,1,1,NaN,NaN,NaN,1,NaN
3,8628223,3,0,10.81,1,0,Simple phobia,2,42,49,...,86,NaN,97,1,1,NaN,NaN,NaN,1,NaN
4,1623716,3,0,12.65,1,1,NaN,2,87,90,...,88,NaN,89,1,1,NaN,NaN,NaN,1,NaN

In [24]:
df_all = pd.concat(dfs, axis=0, ignore_index=True)

In [27]:
df_all.to_csv('../Data/df_all.csv')