#### in this notebook I'm going to try to make a new compressed npz file with the 3d brain data from JUST the 179 patients and the 179 controls with nan ADHD indexes and the lowest remaining indexes

In [2]:
pwd

'/mmfs1/data/bergerar/BC-MRI-ADHD/Code'

In [1]:
import ants
import os 
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

/data/bergerar/anaconda3/lib/python3.8/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "

In [3]:
df = pd.read_csv('../Data/df_440_normed.csv')
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Subject,ScanDir ID,Site,Gender,Age,Handedness,...,QC_Rest_3,QC_Rest_4,QC_Anatomical_1,QC_Anatomical_2,ID,subID,has_brain,ADHD Index Normed,Inattentive Normed,Hyper/Impulsive Normed
0,0,26,26,26,26,2371032.0,3,0.0,10.73,1.0,...,NaN,NaN,1.0,NaN,NaN,sub-2371032,True,0.118644,0.30,0.040816
1,1,27,27,27,27,2026113.0,3,0.0,12.99,1.0,...,NaN,NaN,1.0,NaN,NaN,sub-2026113,True,0.847458,0.98,0.755102
2,2,28,28,28,28,3434578.0,3,0.0,8.12,1.0,...,NaN,NaN,1.0,NaN,NaN,sub-3434578,True,0.033898,0.04,0.040816
3,3,29,29,29,29,8628223.0,3,0.0,10.81,1.0,...,NaN,NaN,1.0,NaN,NaN,sub-8628223,True,0.033898,0.18,0.163265
4,4,30,30,30,30,1623716.0,3,0.0,12.65,1.0,...,NaN,NaN,1.0,NaN,NaN,sub-1623716,True,0.796610,1.00,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,435,707,707,707,707,16081.0,7,1.0,18.81,1.0,...,NaN,NaN,1.0,NaN,NaN,sub-0016081,True,NaN,NaN,NaN
436,436,709,709,709,709,16003.0,7,1.0,10.46,1.0,...,NaN,NaN,0.0,NaN,NaN,sub-0016003,True,NaN,NaN,NaN
437,437,711,711,711,711,16057.0,7,0.0,16.74,1.0,...,NaN,NaN,1.0,NaN,NaN,sub-0016057,True,NaN,NaN,NaN
438,438,714,714,714,714,16023.0,7,0.0,12.51,0.0,...,NaN,NaN,1.0,NaN,NaN,sub-0016023,True,NaN,NaN,NaN
439,439,715,715,715,715,16054.0,7,1.0,16.05,1.0,...,NaN,NaN,1.0,NaN,NaN,sub-0016054,True,NaN,NaN,NaN

In [18]:
def pad_subID(val):
    if np.isnan(val):
            val_str = val
    else:
        val_str = str(int(val))
        if len(val_str)==5:
            val_str = 'sub-00'+val_str
        if len(val_str)==7:
            val_str = 'sub-'+val_str
    return val_str

df['subID'] = [pad_subID(val) for val in df['ScanDir ID'].values]
df.to_csv('../Data/df_440_normed_padded.csv')

In [4]:
brain_dir = '../../Extracted_Brains/'
files = [f for f in os.listdir(brain_dir) if f.endswith('.nii.gz')]
files.sort()
print(len(files))
files[0:5]

596

['sub-0010001_Extracted_Brain.nii.gz',
 'sub-0010002_Extracted_Brain.nii.gz',
 'sub-0010003_Extracted_Brain.nii.gz',
 'sub-0010004_Extracted_Brain.nii.gz',
 'sub-0010005_Extracted_Brain.nii.gz']

In [5]:
fn_temp = '../../Extracted_Brains/{sub}_Extracted_Brain.nii.gz'

In [25]:
df2 = pd.read_csv('../Data/df_440_normed_padded.csv')
df2

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,Subject,ScanDir ID,Site,Gender,Age,...,QC_Rest_3,QC_Rest_4,QC_Anatomical_1,QC_Anatomical_2,ID,subID,has_brain,ADHD Index Normed,Inattentive Normed,Hyper/Impulsive Normed
0,0,0,26,26,26,26,2371032.0,3,0.0,10.73,...,NaN,NaN,1.0,NaN,NaN,sub-2371032,True,0.118644,0.30,0.040816
1,1,1,27,27,27,27,2026113.0,3,0.0,12.99,...,NaN,NaN,1.0,NaN,NaN,sub-2026113,True,0.847458,0.98,0.755102
2,2,2,28,28,28,28,3434578.0,3,0.0,8.12,...,NaN,NaN,1.0,NaN,NaN,sub-3434578,True,0.033898,0.04,0.040816
3,3,3,29,29,29,29,8628223.0,3,0.0,10.81,...,NaN,NaN,1.0,NaN,NaN,sub-8628223,True,0.033898,0.18,0.163265
4,4,4,30,30,30,30,1623716.0,3,0.0,12.65,...,NaN,NaN,1.0,NaN,NaN,sub-1623716,True,0.796610,1.00,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,435,435,707,707,707,707,16081.0,7,1.0,18.81,...,NaN,NaN,1.0,NaN,NaN,sub-0016081,True,NaN,NaN,NaN
436,436,436,709,709,709,709,16003.0,7,1.0,10.46,...,NaN,NaN,0.0,NaN,NaN,sub-0016003,True,NaN,NaN,NaN
437,437,437,711,711,711,711,16057.0,7,0.0,16.74,...,NaN,NaN,1.0,NaN,NaN,sub-0016057,True,NaN,NaN,NaN
438,438,438,714,714,714,714,16023.0,7,0.0,12.51,...,NaN,NaN,1.0,NaN,NaN,sub-0016023,True,NaN,NaN,NaN
439,439,439,715,715,715,715,16054.0,7,1.0,16.05,...,NaN,NaN,1.0,NaN,NaN,sub-0016054,True,NaN,NaN,NaN

In [23]:
#df['has_brain'] = [os.path.exists(fn_temp.format(sub=val)) for val in df['subID'].values]

In [24]:
#brain_df = df.iloc[df['has_brain'].values]
#brain_df['DX'] = pd.to_numeric(brain_df['DX'])
#brain_df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,Subject,ScanDir ID,Site,Gender,Age,...,QC_Rest_3,QC_Rest_4,QC_Anatomical_1,QC_Anatomical_2,ID,subID,has_brain,ADHD Index Normed,Inattentive Normed,Hyper/Impulsive Normed
0,0,0,26,26,26,26,2371032.0,3,0.0,10.73,...,NaN,NaN,1.0,NaN,NaN,sub-2371032,True,0.118644,0.30,0.040816
1,1,1,27,27,27,27,2026113.0,3,0.0,12.99,...,NaN,NaN,1.0,NaN,NaN,sub-2026113,True,0.847458,0.98,0.755102
2,2,2,28,28,28,28,3434578.0,3,0.0,8.12,...,NaN,NaN,1.0,NaN,NaN,sub-3434578,True,0.033898,0.04,0.040816
3,3,3,29,29,29,29,8628223.0,3,0.0,10.81,...,NaN,NaN,1.0,NaN,NaN,sub-8628223,True,0.033898,0.18,0.163265
4,4,4,30,30,30,30,1623716.0,3,0.0,12.65,...,NaN,NaN,1.0,NaN,NaN,sub-1623716,True,0.796610,1.00,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,435,435,707,707,707,707,16081.0,7,1.0,18.81,...,NaN,NaN,1.0,NaN,NaN,sub-0016081,True,NaN,NaN,NaN
436,436,436,709,709,709,709,16003.0,7,1.0,10.46,...,NaN,NaN,0.0,NaN,NaN,sub-0016003,True,NaN,NaN,NaN
437,437,437,711,711,711,711,16057.0,7,0.0,16.74,...,NaN,NaN,1.0,NaN,NaN,sub-0016057,True,NaN,NaN,NaN
438,438,438,714,714,714,714,16023.0,7,0.0,12.51,...,NaN,NaN,1.0,NaN,NaN,sub-0016023,True,NaN,NaN,NaN
439,439,439,715,715,715,715,16054.0,7,1.0,16.05,...,NaN,NaN,1.0,NaN,NaN,sub-0016054,True,NaN,NaN,NaN

In [10]:
#df.iloc[np.isnan(pd.to_numeric(brain_df['DX'],errors='coerce').values)]

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, Unnamed: 0.1.1, Unnamed: 0.1.1.1, Subject, ScanDir ID, Site, Gender, Age, Handedness, DX, Secondary Dx , ADHD Measure, ADHD Index, Inattentive, Hyper/Impulsive, IQ Measure, Verbal IQ, Performance IQ, Full2 IQ, Full4 IQ, Med Status, QC_Rest_1, QC_Rest_2, QC_Rest_3, QC_Rest_4, QC_Anatomical_1, QC_Anatomical_2, ID, subID, has_brain, ADHD Index Normed, Inattentive Normed, Hyper/Impulsive Normed]
Index: []

[0 rows x 34 columns]

In [26]:
def norm(mat):
    return (mat - mat.min()) / (mat.max()-mat.min())

In [28]:
%%time
im_arr = [ants.image_read(fn_temp.format(sub=val)).numpy() for val in df2['subID'].values]
im_arr = np.array(im_arr)
im_arr = np.array([norm(im_arr[i,:,:,:]) for i in range(im_arr.shape[0])])
im_arr.shape

CPU times: user 3.56 s, sys: 697 ms, total: 4.26 s
Wall time: 5.89 s

(440, 64, 64, 64)

In [45]:
# turn nans into zeros to make splicing easier ?
df2['ADHD Index'] = df2['ADHD Index'].replace(np.nan, 0)

In [46]:
df2

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,Subject,ScanDir ID,Site,Gender,Age,...,QC_Rest_3,QC_Rest_4,QC_Anatomical_1,QC_Anatomical_2,ID,subID,has_brain,ADHD Index Normed,Inattentive Normed,Hyper/Impulsive Normed
0,0,0,26,26,26,26,2371032.0,3,0.0,10.73,...,NaN,NaN,1.0,NaN,NaN,sub-2371032,True,0.118644,0.30,0.040816
1,1,1,27,27,27,27,2026113.0,3,0.0,12.99,...,NaN,NaN,1.0,NaN,NaN,sub-2026113,True,0.847458,0.98,0.755102
2,2,2,28,28,28,28,3434578.0,3,0.0,8.12,...,NaN,NaN,1.0,NaN,NaN,sub-3434578,True,0.033898,0.04,0.040816
3,3,3,29,29,29,29,8628223.0,3,0.0,10.81,...,NaN,NaN,1.0,NaN,NaN,sub-8628223,True,0.033898,0.18,0.163265
4,4,4,30,30,30,30,1623716.0,3,0.0,12.65,...,NaN,NaN,1.0,NaN,NaN,sub-1623716,True,0.796610,1.00,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,435,435,707,707,707,707,16081.0,7,1.0,18.81,...,NaN,NaN,1.0,NaN,NaN,sub-0016081,True,NaN,NaN,NaN
436,436,436,709,709,709,709,16003.0,7,1.0,10.46,...,NaN,NaN,0.0,NaN,NaN,sub-0016003,True,NaN,NaN,NaN
437,437,437,711,711,711,711,16057.0,7,0.0,16.74,...,NaN,NaN,1.0,NaN,NaN,sub-0016057,True,NaN,NaN,NaN
438,438,438,714,714,714,714,16023.0,7,0.0,12.51,...,NaN,NaN,1.0,NaN,NaN,sub-0016023,True,NaN,NaN,NaN
439,439,439,715,715,715,715,16054.0,7,1.0,16.05,...,NaN,NaN,1.0,NaN,NaN,sub-0016054,True,NaN,NaN,NaN

In [47]:
allcontrols = df2['DX'].values==0

In [67]:
controls = df2['ADHD Index'].values<42
patients = brain_df['DX'].values!=0

In [60]:
controls

array([False, False,  True,  True, False, False,  True, False, False,
       False,  True,  True,  True, False, False, False, False, False,
        True,  True,  True, False, False,  True, False, False, False,
       False,  True,  True, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False,  True, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False,  True,  True, False, False, False,  True,  True, False,
       False,  True, False, False, False, False, False, False,  True,
        True,  True, False, False, False, False,  True, False,  True,
       False, False,  True, False, False, False,  True, False, False,
       False,  True,  True, False, False, False, False, False,  True,
        True,  True, False, False, False, False,  True, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False,  True, False,  True, False,  True, False, False,
        True,  True, False, False, False,  True, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True, False, False,  True,  True, False,
        True, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False,  True,  True,  True, False, False,
       False, False, False, False, False, False,  True, False, False,
        True, False, False, False,  True,  True,  True, False, False,
        True, False, False, False,  True,  True,  True, False, False,
       False,  True,  True,  True, False, False,  True, False,  True,
       False,  True, False, False, False, False,  True, False, False,
        True, False, False, False, False, False,  True, False,  True,
        True, False,  True, False, False,  True, False, False,  True,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [61]:
patients

array([False,  True, False, False,  True, False, False,  True,  True,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False,  True,
        True, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False, False,  True, False, False, False,
        True, False, False,  True,  True,  True, False,  True,  True,
        True, False, False, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False, False, False,  True, False,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True, False,  True, False, False,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True, False,  True, False,  True, False, False,  True,
       False, False,  True,  True,  True, False,  True, False, False,
        True,  True, False, False,  True, False, False,  True, False,
        True,  True, False, False,  True,  True, False, False,  True,
       False, False,  True,  True,  True, False,  True, False,  True,
        True, False, False, False,  True,  True,  True, False,  True,
        True,  True,  True, False, False,  True, False, False, False,
       False,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True, False, False, False, False,  True,  True,
       False,  True, False, False, False, False, False,  True,  True,
       False, False, False, False,  True,  True, False, False, False,
        True, False,  True,  True,  True, False, False,  True, False,
       False,  True,  True,  True, False,  True, False,  True, False,
       False, False, False,  True,  True, False,  True,  True, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True, False,  True,  True, False,  True,  True, False, False,
       False,  True, False,  True, False,  True, False, False, False,
       False, False,  True,  True, False,  True,  True, False,  True,
        True,  True,  True, False,  True, False,  True, False,  True,
        True, False,  True, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False,  True,  True,
       False,  True, False, False, False,  True,  True, False,  True,
       False,  True, False, False, False,  True,  True,  True, False,
       False,  True, False, False, False, False,  True, False,  True,
       False,  True, False,  True, False, False, False,  True, False,
        True, False, False,  True, False,  True, False, False,  True,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

In [68]:
np.savez_compressed(file='../Assets/brain_array_guess42.npz',data=im_arr,controls=controls,patients=patients)

In [69]:
list(np.load('../Assets/brain_array_guess42.npz').keys())

['data', 'controls', 'patients']